-- ============================================================================
-- Schema del KB del bot Asiri (Dra. Raquel / Clínica Áurea).
-- Correr en el proyecto Supabase target (ujfy...) → SQL Editor → Run.
-- DDL: requiere SQL, no se puede vía service key REST.
-- Después: scripts/reseed_knowledge_base.py para cargar kb/knowledge_base_seed.json
-- ============================================================================

-- 1. Extensión de vectores
create extension if not exists vector;

-- 2. Tabla (embedding 1536 dims = text-embedding-3-small)
create table if not exists public.knowledge_base (
  id        bigint generated by default as identity primary key,
  categoria text,
  titulo    text,
  contenido text,
  metadata  jsonb default '{}'::jsonb,
  embedding vector(1536)
);
-- (Sin índice ivfflat a propósito: con ~35 filas la búsqueda exacta es instantánea.
--  Agregar índice solo si el KB crece a miles.)

-- 3. RPC que invoca el nodo "Supabase Vector Store" de n8n.
--    Devuelve `contenido` aliaseado como `content` (nombre por defecto de LangChain).
--    OJO: el nodo vivo llama `match_documents` (default de LangChain), no `buscar_conocimiento`.
--    Se crean AMBAS con la misma firma/lógica para robustez.
create or replace function public.buscar_conocimiento (
  query_embedding vector(1536),
  match_count int default null,
  filter jsonb default '{}'
) returns table (id bigint, content text, metadata jsonb, similarity float)
language plpgsql stable as $$
begin
  return query
  select kb.id, kb.contenido as content, kb.metadata,
         1 - (kb.embedding <=> query_embedding) as similarity
  from public.knowledge_base kb
  where kb.metadata @> filter
  order by kb.embedding <=> query_embedding
  limit match_count;
end;
$$;

create or replace function public.match_documents (
  query_embedding vector(1536),
  match_count int default null,
  filter jsonb default '{}'
) returns table (id bigint, content text, metadata jsonb, similarity float)
language plpgsql stable as $$
begin
  return query
  select kb.id, kb.contenido as content, kb.metadata,
         1 - (kb.embedding <=> query_embedding) as similarity
  from public.knowledge_base kb
  where kb.metadata @> filter
  order by kb.embedding <=> query_embedding
  limit match_count;
end;
$$;
