-- Historial de cambios de prompts del agente, hecho desde el panel.
-- Permite ver quién cambió qué y REVERTIR a la versión anterior.
create table if not exists public.agente_prompt_log (
  id               bigint generated by default as identity primary key,
  node_name        text        not null,   -- nombre del nodo agente en n8n
  prompt_anterior  text        not null,   -- backup: lo que había antes (para revert)
  prompt_nuevo     text        not null,
  autor            text,
  created_at       timestamptz not null default now()
);
create index if not exists agente_prompt_log_node_idx
  on public.agente_prompt_log (node_name, created_at desc);
alter table public.agente_prompt_log enable row level security;
