"""
Rebuild de la tabla `knowledge_base` en el proyecto Supabase v3 (2026-07-17).

Contexto: el proyecto Supabase v2 (`ujfyapjwrdhnvqdvsjwp`) murio en crash-loop
irrecuperable (ver memory/current-state.md 17/7). Se crea un proyecto v3 nuevo
y hay que reconstruir la KB. La fuente de verdad del contenido es el export que
valido la Dra: `docs/kb-validacion-dra-2026-07-09.md` (35 entradas, ids 1-35).

Que hace este script (cuando se ejecute — NO ejecutar hasta tener el v3 creado):

  1. Parsea el markdown a filas {id, categoria, titulo, contenido, metadata}.
     Preserva los ids originales [N] para mantener referencias historicas.
  2. Genera embeddings text-embedding-3-small (1536 dims). Como NO hay OpenAI
     API key local, crea un workflow TEMPORAL en n8n via API (patron de
     scripts/test_conexion_fresca.py): webhook -> HTTP Request a
     api.openai.com/v1/embeddings con la credencial openAiApi que YA vive en
     n8n -> respond. Texto embebido = "categoria | titulo\\ncontenido" (misma
     receta que scripts/embed_knowledge_base.py, para no cambiar la semantica
     de matching). El workflow temporal se desactiva y BORRA siempre (finally).
  3. Inserta por REST en el v3 (service_role) con upsert por id
     (?on_conflict=id + Prefer: resolution=merge-duplicates) => idempotente.
  4. Verifica: 35 filas, 0 embeddings NULL, y smoke-test de la RPC
     match_documents (el embedding de la fila 1 debe matchearse a si mismo).

Esquema esperado en v3 (identico al v2, el que consume el nodo
`buscar_conocimiento` del v6: tableName=knowledge_base, queryName=match_documents,
que mapea contenido->content). PostgREST NO ejecuta DDL, asi que la tabla y la
funcion hay que crearlas ANTES en el SQL editor del v3:

    python scripts/rebuild_v3_kb.py --print-ddl   # imprime el SQL para pegar

Uso:
    python scripts/rebuild_v3_kb.py --print-ddl   # SQL previo (SQL editor v3)
    python scripts/rebuild_v3_kb.py --dry-run     # solo parsea y muestra filas
    python scripts/rebuild_v3_kb.py               # pipeline completo

Config: completar NEW_REF y SERVICE_ROLE_KEY abajo (o via .env / env vars:
SUPABASE_V3_REF, SUPABASE_V3_SERVICE_ROLE_KEY, N8N_OPENAI_CRED_ID).

Post-run (SQL editor v3, leccion del 8/7 — secuencias post-restore):
    select setval(pg_get_serial_sequence('public.knowledge_base','id'),
                  (select coalesce(max(id),1) from public.knowledge_base));

NOTA: este script NO toca ningun workflow productivo. Solo crea/borra un
workflow TEMP propio. El re-punteo de credenciales de n8n al v3 (Postgres,
"Supabase account", URLs REST) es OTRO paso, con su propio script (patron
scripts/apply_supabase_v2_rewire.py) y OK de Lucas.
"""
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, str(Path(__file__).parent))
from lib_env import env, require

# ============================= CONFIG ========================================
# Ref del proyecto Supabase v3 NUEVO (20 chars, ej: "abcdefghijklmnopqrst").
NEW_REF = env("SUPABASE_V3_REF", "")

# service_role key del proyecto v3 (Settings -> API -> service_role).
SERVICE_ROLE_KEY = env("SUPABASE_V3_SERVICE_ROLE_KEY", "")

# Credencial OpenAI EXISTENTE en n8n (verificada 2026-07-17 via
# GET /api/v1/credentials: type=openAiApi, la usan los 11 nodos LLM del v6).
# Si se deja vacia, el script la autodetecta (GET /credentials, fallback scan v6).
OPENAI_CRED_ID = env("N8N_OPENAI_CRED_ID", "nYujqfon7GGDnJUO")
OPENAI_CRED_NAME = env("N8N_OPENAI_CRED_NAME", "OpenAi account")

KB_MD = Path(__file__).resolve().parents[1] / "docs" / "kb-validacion-dra-2026-07-09.md"
EMBED_MODEL = "text-embedding-3-small"
EMBED_DIMS = 1536
EMBED_BATCH = 16      # textos por llamada a /v1/embeddings
INSERT_BATCH = 10     # filas por POST a PostgREST
V6_WF_ID = "O155MqHgOSaNZ9ye"          # solo para autodetect de credencial (GET)
DEAD_REFS = {"dchztroesbpwxxkfywwu",   # v1, borrado 08/07
             "ujfyapjwrdhnvqdvsjwp"}   # v2, crash-loop 15-17/07
# =============================================================================

DDL = """
-- === knowledge_base v3 (pegar en el SQL editor del proyecto NUEVO) ===
-- Esquema identico al v2: el nodo `buscar_conocimiento` del v6 usa
-- tableName=knowledge_base + queryName=match_documents (contenido->content).

create extension if not exists vector;

create table if not exists public.knowledge_base (
  id         bigint generated by default as identity primary key,
  categoria  text,
  titulo     text,
  contenido  text not null,
  metadata   jsonb not null default '{}'::jsonb,
  embedding  vector(1536),
  created_at timestamptz not null default now()
);

-- Con 35 filas no hace falta indice ANN; si la KB crece (>1k), descomentar:
-- create index if not exists knowledge_base_embedding_idx
--   on public.knowledge_base using ivfflat (embedding vector_cosine_ops)
--   with (lists = 10);

create or replace function public.match_documents (
  query_embedding vector(1536),
  match_count int default null,
  filter jsonb default '{}'::jsonb
) returns table (id bigint, content text, metadata jsonb, similarity float)
language plpgsql as $$
begin
  return query
  select kb.id,
         kb.contenido as content,
         kb.metadata,
         1 - (kb.embedding <=> query_embedding) as similarity
  from public.knowledge_base kb
  where kb.metadata @> filter
    and kb.embedding is not null
  order by kb.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- === POST-INSERT (correr DESPUES de rebuild_v3_kb.py — leccion 8/7) ===
-- select setval(pg_get_serial_sequence('public.knowledge_base','id'),
--               (select coalesce(max(id),1) from public.knowledge_base));
""".strip()


def die(msg):
    print("ABORTADO: " + msg)
    sys.exit(1)


# ---------------------------------------------------------------- 1) parseo
def parse_kb_markdown(path):
    """Parsea el export a [{id, categoria, titulo, contenido}] + total declarado."""
    text = path.read_text(encoding="utf-8")
    m = re.search(r"Total:\s*(\d+)\s*entradas", text)
    declared_total = int(m.group(1)) if m else None

    entries, cat, cur = [], None, None
    for line in text.splitlines():
        h = re.match(r"^##\s+(.+?)\s*$", line)
        t = re.match(r"^\*\*\[(\d+)\]\s*(.+?)\*\*\s*$", line)
        if h:
            cat = h.group(1).strip()
            cur = None
        elif t:
            if cat is None:
                die(f"titulo antes de la primera categoria: {line!r}")
            cur = {"id": int(t.group(1)), "categoria": cat,
                   "titulo": t.group(2).strip(), "lineas": []}
            entries.append(cur)
        elif cur is not None:
            cur["lineas"].append(line)

    out = []
    for e in entries:
        contenido = "\n".join(e["lineas"]).strip()
        if not contenido:
            die(f"entrada [{e['id']}] '{e['titulo']}' quedo sin contenido")
        out.append({"id": e["id"], "categoria": e["categoria"],
                    "titulo": e["titulo"], "contenido": contenido})

    ids = [e["id"] for e in out]
    if len(ids) != len(set(ids)):
        die("ids duplicados en el markdown")
    if declared_total is not None and len(out) != declared_total:
        die(f"el header declara {declared_total} entradas pero parsee {len(out)}")
    return out, declared_total or len(out)


def embed_text_of(e):
    # MISMA receta que scripts/embed_knowledge_base.py (v1/v2):
    # categoria + titulo + contenido juntos = mejor matching semantico.
    return f"{e['categoria']} | {e['titulo']}\n{e['contenido']}"


# ------------------------------------------------------------ 2) n8n helpers
def n8n_api(method, path, body=None):
    n8n = require("N8N_BASE_URL").rstrip("/")
    key = require("N8N_API_KEY")
    h = {"X-N8N-API-KEY": key, "accept": "application/json",
         "content-type": "application/json"}
    data = json.dumps(body, ensure_ascii=False).encode() if body is not None else None
    req = urllib.request.Request(n8n + path, method=method, headers=h, data=data)
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = r.read()
        return json.loads(raw) if raw else None


def detect_openai_cred():
    """Devuelve {id, name} de la credencial openAiApi de n8n."""
    if OPENAI_CRED_ID:
        return {"id": OPENAI_CRED_ID, "name": OPENAI_CRED_NAME or "OpenAi account"}
    # a) listado de credenciales (este n8n SI lo permite, verificado 17/7)
    try:
        cands, cursor = [], ""
        while True:
            page = n8n_api("GET", "/api/v1/credentials" + (f"?cursor={cursor}" if cursor else ""))
            cands += [c for c in page.get("data", []) if c.get("type") == "openAiApi"]
            cursor = page.get("nextCursor")
            if not cursor:
                break
        if len(cands) == 1:
            return {"id": cands[0]["id"], "name": cands[0]["name"]}
        if len(cands) > 1:
            pref = [c for c in cands if c["name"] == OPENAI_CRED_NAME]
            if len(pref) == 1:
                return {"id": pref[0]["id"], "name": pref[0]["name"]}
            die("varias credenciales openAiApi en n8n, fijar OPENAI_CRED_ID: "
                + ", ".join(f"{c['id']}({c['name']})" for c in cands))
    except urllib.error.HTTPError:
        pass  # algunas versiones no exponen GET /credentials -> fallback
    # b) fallback: scan del v6 (solo GET)
    wf = n8n_api("GET", f"/api/v1/workflows/{V6_WF_ID}")
    for n in wf["nodes"]:
        c = (n.get("credentials") or {}).get("openAiApi")
        if c:
            return {"id": c["id"], "name": c.get("name", "OpenAi account")}
    die("no encontre credencial openAiApi ni listando ni en el v6 — fijar OPENAI_CRED_ID")


def embed_via_n8n(texts, cred):
    """Crea workflow TEMP webhook->HTTP(OpenAI embeddings)->respond, embebe
    `texts` en batches y devuelve la lista de vectores (mismo orden).
    El TEMP se desactiva y borra SIEMPRE."""
    n8n = require("N8N_BASE_URL").rstrip("/")
    ts = int(time.time() * 1000) % 10**9
    wh = f"embed-kb-v3-{ts}"
    nodes = [
        {"parameters": {"httpMethod": "POST", "path": wh, "responseMode": "lastNode",
                        "responseData": "allEntries", "options": {}},
         "id": "wh", "name": "Webhook", "type": "n8n-nodes-base.webhook",
         "typeVersion": 2, "position": [200, 300], "webhookId": wh},
        {"parameters": {
            "method": "POST",
            "url": "https://api.openai.com/v1/embeddings",
            "authentication": "predefinedCredentialType",
            "nodeCredentialType": "openAiApi",
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": ("={{ JSON.stringify({ model: '" + EMBED_MODEL + "', "
                         "dimensions: " + str(EMBED_DIMS) + ", "
                         "input: $json.body.texts }) }}"),
            "options": {}},
         "id": "emb", "name": "Embed", "type": "n8n-nodes-base.httpRequest",
         "typeVersion": 4.2, "position": [420, 300],
         "credentials": {"openAiApi": {"id": cred["id"], "name": cred["name"]}}},
    ]
    wf = n8n_api("POST", "/api/v1/workflows",
                 {"name": f"TEMP-embed-kb-v3-{ts}", "nodes": nodes,
                  "connections": {"Webhook": {"main": [[{"node": "Embed", "type": "main", "index": 0}]]}},
                  "settings": {"executionOrder": "v1"}})
    wid = wf["id"]
    print(f"   TEMP workflow {wid} (webhook /{wh})")
    vectors = []
    try:
        n8n_api("POST", f"/api/v1/workflows/{wid}/activate")
        time.sleep(2)
        for i in range(0, len(texts), EMBED_BATCH):
            batch = texts[i:i + EMBED_BATCH]
            payload = json.dumps({"texts": batch}, ensure_ascii=False).encode()
            resp = None
            for intento in range(3):
                req = urllib.request.Request(
                    f"{n8n}/webhook/{wh}", method="POST",
                    headers={"Content-Type": "application/json"}, data=payload)
                try:
                    with urllib.request.urlopen(req, timeout=120) as r:
                        resp = json.loads(r.read())
                    break
                except urllib.error.HTTPError as e:
                    print(f"   batch {i//EMBED_BATCH + 1}: HTTP {e.code}, "
                          f"reintento {intento + 1}/3 en 5s...")
                    time.sleep(5)
            if resp is None:
                die("el webhook TEMP no respondio tras 3 intentos")
            if isinstance(resp, list):          # responseData=allEntries -> [item]
                resp = resp[0]
            data = resp.get("data")
            if not isinstance(data, list) or len(data) != len(batch):
                die("respuesta OpenAI inesperada: " + json.dumps(resp)[:300])
            for item in sorted(data, key=lambda d: d["index"]):
                v = item["embedding"]
                if len(v) != EMBED_DIMS:
                    die(f"embedding de {len(v)} dims (esperaba {EMBED_DIMS})")
                vectors.append(v)
            print(f"   batch {i//EMBED_BATCH + 1}: {len(batch)} textos OK")
    finally:
        try:
            n8n_api("POST", f"/api/v1/workflows/{wid}/deactivate")
        except Exception:
            pass
        try:
            n8n_api("DELETE", f"/api/v1/workflows/{wid}")
            print(f"   TEMP workflow {wid} borrado")
        except Exception as e:
            print(f"   OJO: no pude borrar el TEMP {wid} ({e}) — borrarlo a mano")
    return vectors


# ------------------------------------------------------------ 3) Supabase v3
def supa(method, path, body=None, extra_headers=None):
    h = {"apikey": SERVICE_ROLE_KEY,
         "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
         "Content-Type": "application/json"}
    h.update(extra_headers or {})
    data = json.dumps(body, ensure_ascii=False).encode() if body is not None else None
    req = urllib.request.Request(f"https://{NEW_REF}.supabase.co{path}",
                                 method=method, headers=h, data=data)
    with urllib.request.urlopen(req, timeout=60) as r:
        raw = r.read()
        return r.status, (json.loads(raw) if raw else None)


def vec_str(v):
    return "[" + ",".join(repr(round(x, 8)) for x in v) + "]"


def main():
    dry = "--dry-run" in sys.argv
    if "--print-ddl" in sys.argv:
        print(DDL)
        return

    print(f"1) Parseando {KB_MD.name}...")
    entries, total = parse_kb_markdown(KB_MD)
    print(f"   {len(entries)} entradas (header declara {total}) — "
          f"ids {min(e['id'] for e in entries)}..{max(e['id'] for e in entries)}")
    cats = sorted({e["categoria"] for e in entries})
    print(f"   categorias ({len(cats)}): {', '.join(cats)}")

    if dry:
        for e in entries:
            print(f"   [{e['id']:>2}] {e['categoria']:<15} {e['titulo'][:60]!r} "
                  f"({len(e['contenido'])} chars)")
        print("DRY RUN — no se llama a n8n ni a Supabase.")
        return

    # guardas de config
    if not NEW_REF:
        die("NEW_REF vacio — completar CONFIG o SUPABASE_V3_REF en .env")
    if NEW_REF in DEAD_REFS:
        die(f"NEW_REF={NEW_REF} es un proyecto MUERTO (v1/v2), no el v3")
    if not re.fullmatch(r"[a-z0-9]{20}", NEW_REF):
        die(f"NEW_REF={NEW_REF!r} no parece un ref de Supabase (20 chars a-z0-9)")
    if not SERVICE_ROLE_KEY:
        die("SERVICE_ROLE_KEY vacio — completar CONFIG o SUPABASE_V3_SERVICE_ROLE_KEY en .env")

    print(f"\n2) Chequeando que knowledge_base exista en v3 ({NEW_REF})...")
    try:
        supa("GET", "/rest/v1/knowledge_base?select=id&limit=1")
        print("   tabla OK")
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")[:300]
        die(f"REST v3 fallo (HTTP {e.code}: {body}) — "
            "correr primero el DDL: python scripts/rebuild_v3_kb.py --print-ddl")

    print("\n3) Credencial OpenAI en n8n...")
    cred = detect_openai_cred()
    print(f"   openAiApi id={cred['id']} name={cred['name']!r}")

    print(f"\n4) Embeddings {EMBED_MODEL} ({EMBED_DIMS} dims) via workflow TEMP...")
    vectors = embed_via_n8n([embed_text_of(e) for e in entries], cred)
    if len(vectors) != len(entries):
        die(f"{len(vectors)} vectores para {len(entries)} entradas")

    print(f"\n5) Upsert de {len(entries)} filas en v3 (on_conflict=id)...")
    rows = []
    for e, v in zip(entries, vectors):
        rows.append({
            "id": e["id"],
            "categoria": e["categoria"],
            "titulo": e["titulo"],
            "contenido": e["contenido"],
            "metadata": {"categoria": e["categoria"], "titulo": e["titulo"],
                         "kb_id": e["id"],
                         "fuente": "docs/kb-validacion-dra-2026-07-09.md",
                         "embedding_model": EMBED_MODEL, "dims": EMBED_DIMS},
            "embedding": vec_str(v),
        })
    for i in range(0, len(rows), INSERT_BATCH):
        chunk = rows[i:i + INSERT_BATCH]
        st, _ = supa("POST", "/rest/v1/knowledge_base?on_conflict=id", chunk,
                     {"Prefer": "resolution=merge-duplicates,return=minimal"})
        print(f"   filas {chunk[0]['id']}..{chunk[-1]['id']}: HTTP {st}")

    print("\n6) Verificacion...")
    _, got = supa("GET", "/rest/v1/knowledge_base?select=id&order=id")
    ids_db = [r["id"] for r in got]
    _, nulls = supa("GET", "/rest/v1/knowledge_base?select=id&embedding=is.null")
    print(f"   filas: {len(ids_db)} (esperadas {len(entries)}) — "
          f"embeddings NULL: {len(nulls)} (esperado 0)")
    if len(ids_db) != len(entries) or nulls:
        die("verificacion de filas/embeddings fallo")
    # smoke-test RPC: el embedding de la primera entrada debe devolverse a si mismo
    try:
        _, hits = supa("POST", "/rest/v1/rpc/match_documents",
                       {"query_embedding": rows[0]["embedding"], "match_count": 3})
        top = hits[0] if hits else {}
        ok = top.get("id") == rows[0]["id"] and top.get("similarity", 0) > 0.99
        print(f"   match_documents top-1: id={top.get('id')} "
              f"sim={round(top.get('similarity', 0), 4)} -> {'OK' if ok else 'REVISAR'}")
        if not ok:
            die("match_documents no devolvio la propia fila como top-1")
    except urllib.error.HTTPError as e:
        die(f"RPC match_documents fallo (HTTP {e.code}) — crear la funcion con --print-ddl")

    print("\nLISTO. Pasos siguientes (fuera de este script):")
    print("  a) SQL editor v3: setval de la secuencia (ver --print-ddl, bloque POST-INSERT).")
    print("  b) Rewire de n8n al v3 (patron apply_supabase_v2_rewire.py, CON OK de Lucas):")
    print("     credencial Postgres nueva + 'Supabase account' (Thn3jgEbbxPFD7d9) al host v3 +")
    print("     URLs con el ref viejo en obtener_historial_paciente y tools de recordatorios.")


if __name__ == "__main__":
    main()
